language: node_js
node_js:
  - '10'
script:
  - npm run test -- --ci
  - npm run build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
